-- 코드를 입력하세요
SELECT A.USER_ID, A.PRODUCT_ID
FROM ONLINE_SALE AS A INNER JOIN ONLINE_SALE AS B ON (A.USER_ID = B.USER_ID AND A.PRODUCT_ID = B.PRODUCT_ID)
GROUP BY A.USER_ID, A.PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY A.USER_ID, A.PRODUCT_ID DESC;